//
//  Header.h
//  WeTestForIOS
//
//  Created by caorobin on 15-3-27.
//  Copyright (c) 2015年 caorobin. All rights reserved.
//

/**
 *  常量类
 */
FOUNDATION_EXPORT NSString *const KEY_TARGET;
FOUNDATION_EXPORT NSString *const KEY_TARGET_CLOUD;

FOUNDATION_EXPORT NSString *const SESSION_NAME;
FOUNDATION_EXPORT NSString *const WEB_SESSION_NAME;

FOUNDATION_EXPORT NSString * const KEY_SOALOGIN;
FOUNDATION_EXPORT NSString * const KEY_SOAUPLOAD;

FOUNDATION_EXPORT NSString * const KEY_SQQLOGIN;
FOUNDATION_EXPORT NSString * const KEY_SQQUPLOAD;
FOUNDATION_EXPORT NSString * const KEY_WEBPTLOGINURL;
FOUNDATION_EXPORT NSString * const KEY_WEBPTLOGINFINSHURL;
FOUNDATION_EXPORT NSString * const KEY_WEBALTERPTLOGINFINSHURL;
FOUNDATION_EXPORT NSString * const KEY_WEBOALOGINURL;


FOUNDATION_EXPORT const int RETRY_COUNT;


FOUNDATION_EXPORT NSString * const KEY_SLOGIN;
FOUNDATION_EXPORT NSString * const KEY_SUPLOAD;